- name: Set up managed node
  hosts: hosts
  remote_user: ec2-user
  tasks:
    - name: Install git and python
      ansible.builtin.yum:
        name: 
          - git
          - python3
      become: yes
