name: Continuous Integration/Continuous Deployment
on: 
  schedule:
    - cron: '25 12 * * 5'
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.drawio'
  push:
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.drawio'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build test image
      uses: docker/build-push-action@v6
      with:
        load: true
        tags: todo-app:test
        target: test
    - run: docker run --env-file ./.env.test todo-app:test
  security:
    name: Run snyk to check for vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run snyk
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    if: github.ref_name == 'exercise9' && github.event_name == 'push'
    needs:
      - build
      - security
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          target: production
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:prod , ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${GITHUB_SHA}
      - name: Run webhook
        run: curl -X POST '${{ secrets.AZURE_WEBHOOK_URL }}'